### PR TITLE
Normalize all of carrots base labels

### LINKED ISSUE #28: Normalize Carrots Web Config
Now that we've built out an `-include` action, we should try to build out a config called `carrot` which is true for all projects

```
            Carrot
         /          \
    Carrot Web   Carrot Mobile
                 /            \
           Android             iOS
```

Would really like to normalize this heirarchy up here as much as possible.

Me and @antonelli worked today to get Carrot Mobile solid, so @kylemac if you want to compare carrot web to carrot mobile to see what we can pull to the base?

I also am not sure who threw together `carrots-web`, so perhaps that was me and it's not accurate... Verify that that is accurate before we actually move on to normalize this!

### LINKED ISSUE #30: clear-default-labels Config
Add a Label Config for `clear-default-labels`

As a user, I should be able to add `-import:clear-default-labels`, and it will delete all of the default Github labels.

### PR DESCRIPTION
**Pull request by BrandonRomano**
Fixes #28
Fixes #30 

So this is more of a visual issue, so I'll simply just add screenshots:
# carrots

All other `carrots-*` configurations extend this configuration

screen shot 2016-03-29 at 7 23 21 pm
# carrots-android

Everything in `carrots` +

screen shot 2016-03-29 at 7 24 45 pm
# carrots-ios

Everything in `carrots` +

screen shot 2016-03-29 at 7 26 47 pm
# carrots-web

Everything in `carrots` +

screen shot 2016-03-29 at 7 31 25 pm

### CODE REVIEW

**Comment by BrandonRomano** [comment]
cc @carrot/development + @carrot/qa  .. Open to any and all suggestions!

Just threw this together today in an attempt to normalize our label configs.

**Comment by antonelli** [comment]
Mmm, sexy gradients. I would just suggest making the `priority-high` a brighter color, as you often want to scan the issue list and quickly find anything critical. Also, some labels were removed that I think were valuable. Like the `duplicate` label for QA or `discussion` for the team.

**Comment by jescalan** [comment]
Agreed, same for bug-critical, that should jump out more than any other label

**Comment by antonelli** [comment]
What if we didn't have tiers of `bug-`, instead had a single `bug` label and then using the `priority-` labels to denote how critical the bug is. This will also help when someone reports a bug but doesn't know how critical it is - the PM can then add the critical level.

**Comment by Samkimsamkim** [comment]
This is GREAT. Labels are very robust/flexible and really saves time imo. Also really easy for me to keep track, since I can tackle issues by device/category, and i'm sure devs would like the option to work through issues like that too, especially early on when there are lots to filter through

Also i agree with @antonelli about having priority labels versus separate bug labels.

Some nice to have labels: mostly for other teams so they can track what needs to be done
needs-design for missing font, assets, videos, etc
UX - for ux related questions though that often falls under enhancement/question/discussion
one for analytics?
api - for api related issues?
needs-copy?

**Comment by BrandonRomano** [comment]
Yeah, so I went with "darker colors are the things that require more attention approach"... You can see `blocked`, `bug-critical`, and `priority-high` are the darkest.  I can most definitely flip that around and make the lighter colors require the most attention, but that actually feels almost counter intuitive to me -- but definitely willing to do it if a majority of us feel that way!

**Comment by BrandonRomano** [comment]
I also agree w/ removing the bug tiers, and simply adding `priority-*` tag also to issues that require a different level of attention.

**Comment by antonelli** [comment]
I don't think it's as much about light vs dark as intensity and contrast. Pure black for blocked is an intense and quickly noticeable color on the white contrasting background of github, but dark purple/blue of high-priority doesn't create the same contrast. If the high-priority label were just brighter in intensity it would be more noticeable. The more muted colors work great (and look great in the gradient of colors) for less critical labels.

**Comment by BrandonRomano** [comment]
@antonelli gotcha

I can play around with the colors a bit to make them stand out more!

I will also remove the `bug-` tiers

**Comment by Samkimsamkim** [comment]
Red, yellow, orange,  all nice colors for issue priority with black for blocked

**Comment by BrandonRomano** [comment]
Discussions landed on this:

screen shot 2016-06-30 at 3 28 27 pm

Can update in the future, but merging for now!

**Pull request merged**
