### PR TITLE
Adding carrots-android labels setup

### LINKED ISSUE #12: Create carrots-android label config

### PR DESCRIPTION
**Pull request by BrandonRomano**
Fixes #12

@roideuniverse, can you think of anything else you'd like to see here?  We can always add to it, so not super important right now

### CODE REVIEW

**Comment by roideuniverse** [comment]
Invalid
Heavy Lift
Todo ?

**Comment by roideuniverse** [comment]
not reproducible, need-more-info, for bugs ?

**Comment by BrandonRomano** [comment]
`Invalid`, `Heavy Lift`, `not-reproducible`, and `need-more-info` all seem like good additions.

`TODO` is really implied by the fact that an issue is open, isn't it?

**Comment by roideuniverse** [comment]
Gotcha, I came out with the word `Todo`, but the idea in my mind of was `queued` which sounds similar to `implement` :smile_cat: 

`in-progress` ?

**Comment by BrandonRomano** [comment]
Ah yeah, makes sense.

`in-progress` is also a good addition I think!

**Comment by roideuniverse** [comment]
:+1:  :tada:

**Pull request merged**
